name: 'Gitops Update'
description: 'Updates a key in a gitops repository and commit it'
inputs:
  filename: 
    description: 'Filename to update'
    required: true
  key:  
    description: "The key to update. Key a string before the colon. Usually it's yaml key like `this-is-key: value`"
    required: true
  value:  
    description: "The value to set"
    required: true
  github-deploy-key:  
    description: "Github deploy ssh private key to clone and commit target repository"
    required: true
  github-org-and-repo:  
    description: "Target organization and repository in form of `some-org/repo`"
    required: true

runs:
  using: "composite"
  steps:
    - name: Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0-rc.1
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install dependencies
      run: |
        if [ -f ${{ github.action_path }}/requirements.txt ];then pip install -r ${{ github.action_path }}/requirements.txt; fi
      shell: bash
    - run: ${{ github.action_path }}/run.sh "${{ inputs.filename }}" "${{ inputs.key }}" "${{ inputs.value }}" "${{ inputs.github-deploy-key }}" "${{ inputs.github-org-and-repo }}"
      shell: bash
